Supporting SMART App Launch with Keycloak and the IBM FHIR Server
Alvearie/alvearie.github.io pull request #35
Opened 2021-03-16 18:16 UTC by lmsurpre

my first draft for an upcoming blog post

2021-03-16 20:45 UTC, mannyveiga commented on src/pages/blog/smart-keycloak/index.mdx
> +Keycloak is wonderfully-extensible and easily-configurable.
remove the - marks here

should be "wonderfully extensible and easily configurable"

2021-03-16 20:47 UTC, mannyveiga commented on src/pages/blog/smart-keycloak/index.mdx
> +SMART App Launch is just one of the specification defined by SMART-on-FHIR and the authentication and authorization challenges in healthcare are immense. We'd love to hear from members of the FHIR co
change to plural form - "specifications"

2021-03-16 20:56 UTC, mannyveiga requested changes

2021-03-16 20:56 UTC, mannyveiga commented on src/pages/blog/smart-keycloak/index.mdx
> +Keycloak is wonderfully-extensible and easily-configurable.
```suggestion
Keycloak is wonderfully extensible and easily configurable.
```

2021-03-16 20:56 UTC, mannyveiga commented on src/pages/blog/smart-keycloak/index.mdx
> +SMART App Launch is just one of the specification defined by SMART-on-FHIR and the authentication and authorization challenges in healthcare are immense. We'd love to hear from members of the FHIR co
```suggestion
SMART App Launch is just one of the specifications defined by SMART-on-FHIR and the authentication and authorization challenges in healthcare are immense. We'd love to hear from members of the FHIR community, the SMART-on-FHIR community, and the Keycloak community on the approach outlined here and where you'd like to see us go next. Please connect with us on [chat.fhir.org](https://chat.fhir.org/#narrow/stream/179170-smart/topic/Keycloak.20for.20SMART.20authz), the [Keycloak Extensions for FHIR project](https://github.com/Alvearie/keycloak-extensions-for-fhir), or the [IBM FHIR Server project](https://github.com/ibm/fhir) about how we can take this to the next level.
```

2021-03-16 23:58 UTC, prb112 commented on src/pages/blog/smart-keycloak/index.mdx
> +SMART is the registered trademarks of SMART Technologies ULC in the U.S. and/or other countries.
Perhaps it should follow https://smarthealthit.org/smart-logos-guidelines-for-trademark-use/
I don't think the above is accurate.

2021-03-17 15:41 UTC, lmsurpre commented on src/pages/blog/smart-keycloak/index.mdx
> +SMART is the registered trademarks of SMART Technologies ULC in the U.S. and/or other countries.
Good catch.  I just googled SMART trademark and followed https://www.smarttech.com/en/legal/trademark-guidelines...didn't even realize that there are two entirely different groups claiming trademark on "SMART"...seems problematic.

2021-03-17 15:44 UTC, lmsurpre commented on src/pages/blog/smart-keycloak/index.mdx
> +SMART is the registered trademarks of SMART Technologies ULC in the U.S. and/or other countries.
```suggestion
SMART is a trademark of The Children’s Medical Center Corporation.
```

2021-03-23 13:29 UTC, lmsurpre commented on src/pages/blog/smart-keycloak/index.mdx
> +    - Note: moving forward, we hope to add continuous integration support and publish the built artifacts to Maven Central.
```suggestion
    - Note: moving forward, we hope to publish the built artifacts to Maven Central.
```

2021-03-23 13:49 UTC, merged